Models/ErrorViewModel.cs
namespace ToDoApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/ToDoItem.cs
namespace ToDoApp.Models
{
    public class ToDoItem
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public bool IsComplete { get; set; }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using ToDoApp.Models;

namespace ToDoApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ToDoController.cs
        using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ToDoApp.Data;
using ToDoApp.Migrations;
using ToDoApp.Models;

namespace ToDoApp.Controllers
{
    public class ToDoController : Controller
    {
        private readonly ToDoDatabase _database;

        public ToDoController(ToDoDatabase db)
        {
            _database = db;
        }

        public async Task<IActionResult> Index()
        { 
            var todos = await _database.ToDos.ToListAsync();
            return View(todos);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        public async Task<IActionResult> Add(string newItem) 
        {
            if(newItem != null) {
                var todo = new ToDoItem
                {
                    Title = newItem,
                    IsComplete = false
                };
                _database.ToDos.Add(todo);
                await _database.SaveChangesAsync();
            }
            
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Complete(IEnumerable<int> isComplete)
        {
            if(isComplete != null)
            {
                foreach (var item in isComplete)
                {
                    var todo = _database.ToDos.FirstOrDefault(t => t.Id == item);
                    if(todo != null) {
                        todo.IsComplete = true;
                    }
                }
                _database.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        public IActionResult DeleteAll()
        {
            _database.ToDos.RemoveRange(_database.ToDos);
            _database.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            var todo = _database.ToDos.FirstOrDefault(t => t.Id == id);
            if (todo != null)
            {
                _database.ToDos.Remove(todo);
                _database.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1>This is my todo home page </h1>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ToDoApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ToDoApp.styles.css" asp-append-version="true" />

    <style>
        body {
            background-color: #e9f2f9;
            color: #444;
        }

        input[type="text"],
        input[type="submit"],
        input[type="checkbox"] {
            background-color: #c5d5e5;
            color: #444;
            border: none;
            padding: 5px;
            margin-bottom: 10px;
        }

        input[type="submit"] {
            cursor: pointer;
        }

        div {
            display: flex;
            align-items: center;
        }

        span {
            margin-left: 10px;
        }
    </style>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ToDoApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ToDo" asp-action="Index">ToDo</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ToDoApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/ToDo/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model List<ToDoItem>

<h2>ToDo List</h2>

<form method="post" action="@Url.Action("Add")">
    <input type="text" name="newItem" />
    <input type="submit" value="Add" />
</form>


 

@foreach (var todo in Model)
{
<div>
<input type="checkbox" name="isComplete" value="@todo.Id" @(todo.IsComplete ? "checked" : "")/>
<span>@todo.Title</span>
<form method="post" action="@Url.Action("Delete")" style="display: inline-block;">
<input type="hidden" name="id" value="@todo.Id" />
<input type="submit" value="Remove" />
</form>
</div>
}

@if (Model.Any())
{
    <form method="post" action="@Url.Action("DeleteAll")" style="margin-top: 20px;">
        <input type="submit" value="Remove All" />
    </form>
}

<h3>Remain Tasks</h3>

@foreach (var todo in Model.Where(t => !t.IsComplete))
{
<div>
<input type="checkbox" name="isComplete" value="@todo.Id" />
<span>@todo.Title</span>
<form method="post" action="@Url.Action("Delete")" style="display: inline-block;">
<input type="hidden" name="id" value="@todo.Id" />
<input type="submit" value="Remove" />
</form>
</div>
}